language: haskell
install:
  - "cabal install --dry-run -v3"
  - "travis_retry cabal install --only-dependencies --force-reinstalls"
script:
  - "cabal test --jobs=1"
notifications:
  email:
    recipients: travis@silk.co
    on_success: change
    on_failure: change
